### PR TITLE
fix slider not working properly when camera mode is set to perspective

### PR DESCRIPTION
**Pull request by alesmasiar**
Hi,

I've created an issue for this, but after a while I managed to find a fix.

https://github.com/brogan89/MinMaxSlider/issues/6

### CODE REVIEW

**Comment by brogan89** [comment]
Cool looks good. Could you please format it to use tab spacing? The indentation is off. After that, I'll merge it 👍
Thanks.

**Comment by alesmasiar** [comment]
Oh, I see, sorry, I didn't even notice, I have my Visual Studio set to spaces. Should be fixed now.

I have few more things I need to add on my side, to be able to use this in my project, but I think it may be useful to others as well, so maybe I can make a PR for those as well.

The first thing is to be able to set the values without notifying listeners, something like this

	public void SetValues(float minValue, float maxValue, float minLimit, float maxLimit, bool notify = true)
	{
		this.minValue = wholeNumbers ? Mathf.RoundToInt(minValue) : minValue;
		...
	 	 
		if (notify)
		{
			// event
			onValueChanged.Invoke(this.minValue, this.maxValue);
		}
	}

The second thing is, I found out that when you rotate the Canvas containing the slider, the handle movement is off (they fly away in z axis I think), so I am currently working on that as well.

So if you would like for me to make the PR, just let me know.

**Comment by brogan89** [comment]
Sounds good about the no notify param. That's a good addition. You can include it in this PR if you want. 

> The second thing is, I found out that when you rotate the Canvas containing the slider, the handle movement is off (they fly away in z axis I think), so I am currently working on that as well.

Yeah, I had a bit of a play around with a world canvas this morning. I've never had the need for it so didn't design the slider with world space canvases in mind and I spotted a few issues with it. I can see it would be good for VR applications though so I think the support would be nice. 

I appreciate you working on that. You can create a new PR for that one though.

**Comment by alesmasiar** [comment]
I've added the notify param to the PR.

So I'll see if I can figure something out with the world positions. VR is exactly what I need it for.

**Pull request merged**
